include:
  - project: phonexia/dev/technologies/microservices/ci-templates
    ref: PLAT-546-create-pypi-package
    file:
      - /templates/common.yml
      - /templates/renovate.yml
      - /templates/protofiles-public/build.yml
      - /templates/protofiles-public/publish-pypi.yml

